### ISSUE TITLE
Add an image

### ISSUE THREAD

**Issue by mademone** [HackingHistory/hh-project-11ty-starter-kit#7]
I would like to learn how to add an image to a page.

**Comment by titaniumbones** [comment]
will you store the image locally or link to a remote image? 

If it's remote, then it's eas, you just use the standard markdown image link syntax:

`![some image -- this wil lbe rendered if something wrong with the image, or for non-visual browsers](https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png)`

alternatively, you cna create a new directory `src/img` and put your local images there.  Then link to them in this way: 
`![some image -- note the link syntac, which starts with ../img/, that is , double period, then slash](../img/cat.png)`

does that help?

**Comment by mademone** [comment]
This worked nicely! Thank you. Closing issue.
