### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by mademone** [HackingHistory/hh-project-11ty-starter-kit#8]
Would like to change font to a goolge font: <https://fonts.google.com/specimen/Inter?preview.text=Canadian%20History%20Curriculum%20Project&preview.text_type=custom>.

**Comment by titaniumbones** [comment]
this will be easy.  Here's an example of how this is done; can you try on your own and I can give you hints if you run into difficulty?

https://www.w3schools.com/css/css_font_google.asp

**Comment by titaniumbones** [comment]
actually, there's a more efficient way to do it if you would like.  THere are instructions on line 113 of `src/about.md` but they are a bit telegraphic. Here is some more detail

- Go to this url and customize the fonts you'd like to use: https://google-webfonts-helper.herokuapp.com/fonts/inter?subsets=latin,latin-ext
- now download the various font files & put them in `src/fonts`.  Remove baloo if you like, or leave for now.  
- go to `src/sass/_fonts.scss` and replace baloo lines with the code that is presented to you on the above link after you have selected exactly what fonts you want.  
- on line 40 of `src/sass/_theme.scss` replace "Baloo 2" with "Inter"

I think that hshould do it.  There's one more mention of baloo on line 12 of `src/_generate/socialtemplate.njk`, but I think you can safely leave that for now.   

let me know how it goes.

**Comment by mademone** [comment]
This request has been successfully actioned. Closing issue. Thank you.
